project_id = "wudwwgobdpimqbgjypvq"

[functions.generate-insights]
verify_jwt = true

[functions.upload-photo]
verify_jwt = false

[functions.get-photo-url]
verify_jwt = false

[functions.process-article]
verify_jwt = true

[functions.process-insight-job]
verify_jwt = false
